In [1]:
import numpy as np
import pandas as pd

# NO. 1

In [2]:
start = int(input('Masukkan Angka Start : '))
end = int(input('masukkan Angka End : '))

Masukkan Angka Start : 1
masukkan Angka End : 28


In [11]:
# 2 DIMENSI
d2 = np.arange(start, end)
d2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [13]:
# 3 DIMENSI
d2.reshape(3,3,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

# NO.2

In [15]:
banyak = int(input('Banyak Data : '))
mulai = int(input('Mulai : '))
selesai = int(input('Selesai : '))

Banyak Data : 16
Mulai : 1
Selesai : 50


In [26]:
no2 = np.random.randint(1,50,16)
no2

array([30,  3,  4, 19, 35, 26, 15, 46, 19, 46, 16, 31, 33, 33, 41,  6])

In [28]:
no22 = no2.reshape(4,4)
no22

array([[30,  3,  4, 19],
       [35, 26, 15, 46],
       [19, 46, 16, 31],
       [33, 33, 41,  6]])

In [34]:
no222 = np.fliplr(no22)
no222

array([[19,  4,  3, 30],
       [46, 15, 26, 35],
       [31, 16, 46, 19],
       [ 6, 41, 33, 33]])

# NO 3

In [37]:
zero = np.zeros((10,10))
zero

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

# NO 4

In [39]:
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 
          'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 
          's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
my_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
          13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
          23, 24, 25, 26]
pd.Series(my_list, labels)

a     1
b     2
c     3
d     4
e     5
f     6
g     7
h     8
i     9
j    10
k    11
l    12
m    13
n    14
o    15
p    16
q    17
r    18
s    19
t    20
u    21
v    22
w    23
x    24
y    25
z    26
dtype: int64

# NO 5

In [47]:
data1 = np.random.randint(1,5,100)
data11 = pd.Series(data1)
data11

0     1
1     2
2     2
3     1
4     3
     ..
95    2
96    2
97    1
98    4
99    3
Length: 100, dtype: int32

In [57]:
data111 = data11.value_counts()
data111

4    29
1    28
2    24
3    19
dtype: int64

In [67]:
a = [4, 29]
b = [1, 28]
c = [2, 24]
d = [3, 19]
a

[4, 29]

In [68]:
data1111 = pd.DataFrame(data = [a,b,c,d],
                       index = '0 1 2 3'.split(),
                       columns = 'Value Frequency'.split())
data1111 

Value  Frequency
0      4         29
1      1         28
2      2         24
3      3         19

In [69]:
data1111.head(2)

Value  Frequency
0      4         29
1      1         28

# NO 6

In [2]:
import seaborn as sns

In [3]:
df = sns.load_dataset('mpg')
df.head(5)

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0   
1  15.0          8         350.0       165.0    3693          11.5   
2  18.0          8         318.0       150.0    3436          11.0   
3  16.0          8         304.0       150.0    3433          12.0   
4  17.0          8         302.0       140.0    3449          10.5   

   model_year origin                       name  
0          70    usa  chevrolet chevelle malibu  
1          70    usa          buick skylark 320  
2          70    usa         plymouth satellite  
3          70    usa              amc rebel sst  
4          70    usa                ford torino

In [84]:
df.describe(include = object)

origin        name
count     398         398
unique      3         305
top       usa  ford pinto
freq      249           6

In [85]:
df.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model_year', 'origin', 'name'],
      dtype='object')

In [86]:
df.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model_year      0
origin          0
name            0
dtype: int64

# NO 7

In [107]:
nan = df.isna()
nan

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    False      False         False       False   False         False   
1    False      False         False       False   False         False   
2    False      False         False       False   False         False   
3    False      False         False       False   False         False   
4    False      False         False       False   False         False   
..     ...        ...           ...         ...     ...           ...   
393  False      False         False       False   False         False   
394  False      False         False       False   False         False   
395  False      False         False       False   False         False   
396  False      False         False       False   False         False   
397  False      False         False       False   False         False   

     model_year  origin   name  
0         False   False  False  
1         False   False  False  
2         False   False  False  
3         False   False  False  
4         False   False  False  
..          ...     ...    ...  
393       False   False  False  
394       False   False  False  
395       False   False  False  
396       False   False  False  
397       False   False  False  

[398 rows x 9 columns]

In [123]:
nan1 = nan.sort_values("horsepower", ascending = False)
nan1.head(6)

mpg  cylinders  displacement  horsepower  weight  acceleration  \
330  False      False         False        True   False         False   
32   False      False         False        True   False         False   
354  False      False         False        True   False         False   
126  False      False         False        True   False         False   
374  False      False         False        True   False         False   
336  False      False         False        True   False         False   

     model_year  origin   name  
330       False   False  False  
32        False   False  False  
354       False   False  False  
126       False   False  False  
374       False   False  False  
336       False   False  False

In [ ]:
nan

# NO 8

In [131]:
df.groupby('origin')

In [136]:
by_origin = df.groupby('origin')
by_origin.mean('horsepower')

mpg  cylinders  displacement  horsepower       weight  \
origin                                                                
europe  27.891429   4.157143    109.142857   80.558824  2423.300000   
japan   30.450633   4.101266    102.708861   79.835443  2221.227848   
usa     20.083534   6.248996    245.901606  119.048980  3361.931727   

        acceleration  model_year  
origin                            
europe     16.787143   75.814286  
japan      16.172152   77.443038  
usa        15.033735   75.610442

# NO 9

In [4]:
df.head()

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0   
1  15.0          8         350.0       165.0    3693          11.5   
2  18.0          8         318.0       150.0    3436          11.0   
3  16.0          8         304.0       150.0    3433          12.0   
4  17.0          8         302.0       140.0    3449          10.5   

   model_year origin                       name  
0          70    usa  chevrolet chevelle malibu  
1          70    usa          buick skylark 320  
2          70    usa         plymouth satellite  
3          70    usa              amc rebel sst  
4          70    usa                ford torino

In [5]:
df['horse_origin'] = 'lower' + df['origin']
df

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0          8         307.0       130.0    3504          12.0   
1    15.0          8         350.0       165.0    3693          11.5   
2    18.0          8         318.0       150.0    3436          11.0   
3    16.0          8         304.0       150.0    3433          12.0   
4    17.0          8         302.0       140.0    3449          10.5   
..    ...        ...           ...         ...     ...           ...   
393  27.0          4         140.0        86.0    2790          15.6   
394  44.0          4          97.0        52.0    2130          24.6   
395  32.0          4         135.0        84.0    2295          11.6   
396  28.0          4         120.0        79.0    2625          18.6   
397  31.0          4         119.0        82.0    2720          19.4   

     model_year  origin                       name horse_origin  
0            70     usa  chevrolet chevelle malibu     lowerusa  
1            70     usa          buick skylark 320     lowerusa  
2            70     usa         plymouth satellite     lowerusa  
3            70     usa              amc rebel sst     lowerusa  
4            70     usa                ford torino     lowerusa  
..          ...     ...                        ...          ...  
393          82     usa            ford mustang gl     lowerusa  
394          82  europe                  vw pickup  lowereurope  
395          82     usa              dodge rampage     lowerusa  
396          82     usa                ford ranger     lowerusa  
397          82     usa                 chevy s-10     lowerusa  

[398 rows x 10 columns]