In [3]:
import time
import numpy as np
 
size_of_vec = 1000000

def pure_python_function () :
    t1 = time.time()
    X = range(size_of_vec)
    Y = range(size_of_vec)
    Z = [X[i] + Y[i] for i in range(len(x))]
    return time.time() - t1

def numpy_version () :
    t1 = time.time()
    X = np.arrange(size_of_vec)
    Y = np.arrange(size_of_vec)
    Z = X + Y
    reutrn time.time() - t1

t1 = pure_python_function ()
t2 = numpy_version ()

print(f'''waktu running pure python adalah {round(t1,4)}) detik.
Waktu running versi numpy adalah {round(t2,4)} detik.
Numpy di contoh ini {(round((t1/t2),4))} kali lebih cepat!''')

SyntaxError: invalid syntax (<ipython-input-3-81bfe690b703>, line 18)

In [17]:
mylist = [1,2,3]
mylist

[1, 2, 3]

In [19]:
type(mylist)

list

In [21]:
np.array(mylist)

array([1, 2, 3])

In [23]:
mymatrix = [[1,2,3],[4,5,6],[7,8,9]]
mymatrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [25]:
np.array(mymatrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
mylist3 = [
    [[1,2,3], [4,5,6], [7,8,9]],
    [[10,11,12], [13,14,15], [16,17,18]],
    [[19,20,21], [22,23,24], [25,26,27]]
]
mylist3

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
 [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
 [[19, 20, 21], [22, 23, 24], [25, 26, 27]]]

In [28]:
np.array(mylist3)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [32]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [44]:
np.zeros(3)
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [46]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [48]:
np.ones(3)

array([1., 1., 1.])

In [51]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [58]:
np.eye(15)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.

In [64]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [69]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [71]:
np.random.rand(5,5)

array([[0.40579245, 0.02953614, 0.57148849, 0.44682848, 0.24432624],
       [0.22831879, 0.19418112, 0.11408283, 0.2170853 , 0.8857274 ],
       [0.92744193, 0.78890976, 0.61471119, 0.12280308, 0.23870421],
       [0.71765191, 0.10662176, 0.96692471, 0.29461157, 0.04917325],
       [0.46545501, 0.39506255, 0.73619044, 0.1645975 , 0.69230707]])

In [75]:
np.random.randn(2)

array([0.4809827 , 1.09767384])

In [77]:
np.random.randn(5,5)

array([[ 1.40634622,  1.52201259, -2.13495049,  0.68933445, -0.23741683],
       [-0.97313116, -0.70773444,  0.09575253,  1.55335009, -0.11902055],
       [ 1.02026238,  0.33275731,  0.12840487,  1.74947966, -0.23588025],
       [ 0.54228705, -0.94174863,  0.00853813,  1.24335001,  1.32905056],
       [ 0.76182892,  1.56995948,  0.48282833,  0.56133155,  0.55195   ]])

In [90]:
np.random.randint(1,10)

8

In [93]:
np.random.randint(1,101,100)

array([78, 28, 70, 55, 61, 36, 87, 72, 65, 99, 61, 83, 31, 64, 45, 79, 35,
       99, 52, 40, 64, 20, 24, 51, 47, 90, 27, 22, 18, 69, 47, 44, 25, 86,
       74, 17, 55, 46, 27, 27, 60, 58, 56, 77, 29, 32, 74, 53, 90, 35, 37,
       58, 63, 48, 62, 61, 57, 11, 98, 91, 99, 36, 34, 15, 81, 96, 50, 21,
       75, 27, 20, 57,  6, 26, 15, 39, 56, 16, 52, 99, 14,  5, 48, 85, 27,
       47, 44, 38,  9, 15, 48, 96, 88, 47, 36, 68, 88, 20, 74, 60])

In [96]:
mylist = [1,2,3]
array_1d = np.array(mylist)

mymatrix = [[1,2,3],[4,5,6],[7,8,9]]
array_2d = np.array(mymatrix)

mylist3 = [
    [[1,2,3], [4,5,6], [7,8,9]],
    [[10,11,12], [13,14,15], [16,17,18]],
    [[19,20,21], [22,23,24], [25,26,27]]
]
array_3d = np.array(mylist3)


In [98]:
array_1d

array([1, 2, 3])

In [100]:
array_1d.shape

(3,)

In [102]:
array_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [105]:
array_2d.shape

(3, 3)

In [107]:
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [109]:
array_3d.shape

(3, 3, 3)

In [111]:
arr = np.arange(0,25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [113]:
arr.shape

(25,)

In [116]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [119]:
arr.reshape(1,25).shape

(1, 25)

In [121]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [125]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [129]:
array_2d.reshape(-1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [131]:
array_3d.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [133]:
array_2d.reshape(-1).shape

(9,)

In [135]:
array_3d.reshape(-1).shape

(27,)

In [138]:
randarr = np.random.randint(1,50,10)
randarr

array([27, 31,  8, 15, 28, 44, 39, 22, 10,  6])

In [140]:
randarr.max()

44

In [142]:
randarr.argmax()

5

In [144]:
randarr.min()

6

In [146]:
randarr.argmin()

9

# INDEX ARRAY

In [149]:
#CREATING SAMPLE ARRAY
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [151]:
#GET A VALUE AT AN INDEX
arr[8]

8

In [155]:
#GET VALUES IN A RANGE
arr[1:6]

array([1, 2, 3, 4, 5])

In [164]:
#SETTING A VALUE WITH AN INDEX RANGE
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [160]:
#RESET ARRAY, WE WILL SEE WHY I HAD TO RESET IN A MOMENT
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [162]:
#IMPORTANT NOTES ON SLICES
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [174]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [176]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [178]:
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [180]:
arr_2d = np.array(([5,10,15], [20,25,30], [35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [182]:
arr_2d[1]

array([20, 25, 30])

In [187]:
arr_2d[2,2]

45

In [190]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [192]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [194]:
arr_2d[:,2]

array([15, 30, 45])

# FANCY INDEXING


In [5]:
import numpy as np

In [6]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [201]:
[arr[2], arr[5], arr[9]]

[2, 5, 9]

In [203]:
arr[[2,5,9]]

array([2, 5, 9])

In [206]:
arr[[9,2,5]]

array([9, 2, 5])

In [208]:
arr_2d[[0,2]]

array([[ 5, 10, 15],
       [35, 40, 45]])

In [210]:
arr > 4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [212]:
bool_arr = arr > 4
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [215]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [7]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

# NUMPY OPERATION

In [8]:
import numpy as np

In [10]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr +1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
1/arr

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667, 0.14285714, 0.125     , 0.11111111])

In [20]:
arr * arr

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [23]:
2 * arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [25]:
arr_2d = arr.reshape(3,3)
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
arr_2d**2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]], dtype=int32)

In [27]:
arr_1d = np.array([1,2,3])
arr_1d

array([1, 2, 3])

In [28]:
arr_2d * arr_1d

array([[ 1,  4,  9],
       [ 4, 10, 18],
       [ 7, 16, 27]])

In [29]:
arr_2d / arr_2d

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [30]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

In [31]:
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [32]:
np.sin(arr_2d)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])

In [33]:
np.log(arr_2d)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [34]:
np.insert(arr,5,10)

array([ 1,  2,  3,  4,  5, 10,  6,  7,  8,  9])

In [35]:
np.delete(arr,7)

array([1, 2, 3, 4, 5, 6, 7, 9])

In [36]:
np.append(arr,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11])

In [37]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [38]:
b = np.array([[5,6]])
b

array([[5, 6]])

In [39]:
np.concatenate((a,b), axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [41]:
np.concatenate((a,b.T), axis = 1)

array([[1, 2, 5],
       [3, 4, 6]])

In [43]:
np.concatenate((a,b), axis = None)

array([1, 2, 3, 4, 5, 6])

In [44]:
np.where(arr>5,1,arr)

array([1, 2, 3, 4, 5, 1, 1, 1, 1])

In [45]:
np.where(arr>5,1,0)

array([0, 0, 0, 0, 0, 1, 1, 1, 1])

In [47]:
np.where(arr_2d<=5,0,arr_2d)

array([[0, 0, 0],
       [0, 0, 6],
       [7, 8, 9]])